# Generated by Django 3.0.4 on 2020-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='size',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
